#!/bin/bash

user_arn=$(aws sts get-caller-identity --query Arn --output text)
role_arn=$(aws iam list-roles --query "Roles[?contains(AssumeRolePolicyDocument.Statement[0].to_string(Principal),\`${user_arn}\`)].[Arn]" --output text | fzf)

AWS_STS_CREDENTIALS=$(aws sts assume-role --role-arn "${role_arn}" --role-session-name AWSCLI-Session)
AWS_ACCESS_KEY_ID=$(echo "$AWS_STS_CREDENTIALS" | jq -r '.Credentials.AccessKeyId')
AWS_SECRET_ACCESS_KEY=$(echo "$AWS_STS_CREDENTIALS" | jq -r '.Credentials.SecretAccessKey')
AWS_SESSION_TOKEN=$(echo "$AWS_STS_CREDENTIALS" | jq -r '.Credentials.SessionToken')

echo export AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID"
echo export AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY"
echo export AWS_SESSION_TOKEN="$AWS_SESSION_TOKEN"
