#!/usr/bin/env ruby

b = `git branch -a --format "%(refname)" | sd "refs/heads/" "" | sd "refs/" "" | fzf`.chomp

commands = ''
commands += "Checkout\n"
commands += "New Branch from '#{b}'\n"
commands += "Copy branch name\n"
commands += "Delete"

puts cmd = `echo "#{commands}" | fzf`.chomp

case cmd
when 'Checkout'
  `git switch #{b.gsub(/remotes\/origin\//, '')}`
when /New Branch from.*/
  print 'New branch name: '
  new = gets
  `git switch -c #{new.chomp} #{b}`
when 'Copy branch name'
  `echo #{b} | pbcopy`
when 'Delete'
  `git branch -D #{b}`
end
