#!/bin/bash

set -xe

dev-source-update
cindex -no-follow-symlinks -reset -exclude ~/.cindex_excludes ~/src

cd ~/src/github.com/takaishi/takaishi
git stash pop
homesick link --force takaishi

brew bundle
brew update && brew upgrade && brew cleanup

dev-install-ruby

