#!/usr/bin/env ruby
require "date"

arg = ARGV.shift
date = arg ? Date.parse(arg) : Date.today

title = date.strftime("%Y-%m-%d")
prev_title = (date - 1).strftime("%Y-%m-%d")
next_title = (date + 1).strftime("%Y-%m-%d")
year_month_day = date.strftime("%Y-%m-%d")
year = date.strftime("%Y")
year_month = date.strftime("%Y-%m")
month_day = date.strftime("%m-%d")

n_years_ago =
  2020.upto(year.to_i - 1).
    map { |y| Date.parse(date.strftime("#{y}-%m-%d")) }.
    select { |d| d >= Date.new(2019, 8, 23) }.
    map { |d| d.strftime("[%Y-%m-%d]") }.
    join("\n")


puts <<~STRING
 #{title}
 
 [*** 今日の n 年前]
 
 #{n_years_ago}
 
 [*** ナビ]
 
 前日 [#{prev_title}]
 翌日 [#{next_title}]
 
 
 #Journal ##{year_month_day} ##{year} ##{year_month} ##{month_day}
STRING
