name: check changes
description: Check if there are changes in a specified path

inputs:
  path:
    description: 'Path to check for changes'
    required: true

outputs:
  has_changes:
    description: 'Whether there are changes in the specified path'
    value: ${{ steps.check_changes.outputs.has_changes }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.base.sha }}

    - name: Check for changes in ${{ inputs.path }} directory
      id: check_changes
      shell: bash
      run: |
        count=`git diff --name-only ${{ github.event.pull_request.base.sha }}.. -- ${{ inputs.path }} | wc -l`
        if [ $count -eq 0 ]; then
          echo "has_changes=0" >> $GITHUB_OUTPUT
        else
          echo "has_changes=1" >> $GITHUB_OUTPUT
        fi
