name: foo

on:
  push:
    branches:
      - main
permissions:
  contents: read
  pull-requests: write

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Get the commit hash of the merged pull request"
        id: get_commit_hash
        shell: bash
        run: |
          echo "commit_hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: "Search the pull request number by the commit hash of the merged pull request"
        id: get_pr_number
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          debug: true
          script: |
            const commit_hash = "${{ steps.get_commit_hash.outputs.commit_hash }}";
            const { data: { items } } = await github.rest.search.issuesAndPullRequests({
              q: `${commit_hash} type:pr is:merged`
            });
            const pr_number = items[0].number;
            console.log(`The pull request number is ${pr_number}`);
            return pr_number;

      - run: |
          echo ${{ toJSON(github) }}
        shell: bash

