name: foo

on:
  pull_request:
    paths:
      - "foo/**"

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      has_changes: ${{ steps.check_changes.outputs.has_changes }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.sha }}

      - uses: actions/checkout@v3

      - run: |
          git diff --diff-filter=AM --name-only ${{ github.event.pull_request.base.sha }}..

      - name: Check for changes in 'my_directory' directory
        id: check_changes
#        env:
#          BASE_SHA: ${{ github.event.pull_request.base.sha }}
#          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          git diff --diff-filter=AM --name-only ${{ github.event.pull_request.base.sha }}.. -- foo/bar
          git diff --quiet --name-only ${{ github.event.pull_request.base.sha }}.. -- foo/bar
          echo "has_changes=$?" >> $GITHUB_OUTPUT

  check:
    runs-on: ubuntu-latest
    needs: [check_changes]
    steps:
      - uses: actions/checkout@v3

      - run: echo ${{ needs.check_changes.outputs.has_changes }}

      - name: aaa
        if: ${{ needs.check_changes.outputs.has_changes == '1' }}
        run: echo aaaaaaaa

      - name: bbb
        if: ${{ needs.check_changes.outputs.has_changes != '1' }}
        run: echo bbbbbbbb
