name: foo

on:
  pull_request:
    paths:
      - "foo/**"

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      has_changes: ${{ steps.check_changes.outputs.has_changes }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.sha }}
      - uses: actions/checkout@v3
      - name: Check for changes in 'my_directory' directory
        id: check_changes
        run: |
          echo ===========================================
          git diff --name-only ${{ github.event.pull_request.base.sha }}..
          echo ===========================================
          git diff --name-only ${{ github.event.pull_request.base.sha }}.. -- foo/aaa/
          echo ===========================================
          git diff --name-only ${{ github.event.pull_request.base.sha }}.. -- foo/aaa/ | wc -l
          echo ===========================================
          count=`git diff --name-only ${{ github.event.pull_request.base.sha }}.. -- foo/hoge | wc -l`
          echo ===========================================
          echo $count
          if [ $count -eq 0 ]; then
            echo "has_changes=0" >> $GITHUB_OUTPUT
          else
            echo "has_changes=1" >> $GITHUB_OUTPUT
          fi

  check:
    runs-on: ubuntu-latest
    needs: [check_changes]
    steps:
      - uses: actions/checkout@v3

      - run: echo ${{ needs.check_changes.outputs.has_changes }}

      - name: aaa
        if: ${{ needs.check_changes.outputs.has_changes == '1' }}
        run: echo aaaaaaaa

      - name: bbb
        if: ${{ needs.check_changes.outputs.has_changes != '1' }}
        run: echo bbbbbbbb
